apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: schedule-ovirt-cleanup-old-vms
  namespace: ovirt
spec:
  schedule: 20 * * * *
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 200
  successfulJobsHistoryLimit: 3
  suspend: true
  jobTemplate:
    spec:
      template:
        metadata:
          name: schedule-ovirt-cleanup-old-vms
        spec:
          containers:
          - name: ovirt-cleanup-old-vms
            image: quay.io/eslutsky/ansible-runner
            imagePullPolicy: Always
            command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -euo pipefail
              if [ `id -u` -ge 500 ];then
                echo "runner:x:`id -u`:`id -g`:,,,:/runner:/bin/bash\" > /tmp/passwd
                cat /tmp/passwd >> /etc/passwd
                rm /tmp/passwd
              fi
              mkdir -p ~/.ssh/
              chmod 700 ~/.ssh/
              cat <<__EOF__ >~/.ansible.cfg
              [defaults]
              host_key_checking= False
              __EOF__
              cat <<__EOF__ >>~/.ssh/config
              Host *
              StrictHostKeyChecking no
              __EOF__
              chmod 400 ~/.ssh/config
              set -o allexport
              source /etc/openshift-installer/ovirt.conf
              cd /tmp/scripts
              ansible-playbook ovirt_remove_old_vms.yaml -vvv
              "
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /runner/gcp-secrets
              name: config-gcp-secrets
            - mountPath: /tmp/shared
              name: shared-tmp
            - mountPath: /etc/openshift-installer
              name: cluster-profile
            - mountPath: /tmp/scripts
              name: scripts
          volumes:
          - name: config-gcp-secrets
            secret:
              defaultMode: 420
              secretName: ovirt-infra-gcp-secrets
          - emptyDir: {}
            name: shared-tmp
          - name: cluster-profile
            secret:
              defaultMode: 420
              secretName: cluster-secrets-ovirt
          - configMap:
              defaultMode: 420
              name: ocp-on-rhv-ci-scripts
            name: scripts
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30

status:
  lastScheduleTime: "2020-05-14T07:20:00Z"
